### ISSUE TITLE
AdGuard 设置不是 DNS封锁清单

### ISSUE THREAD

**Issue by yer2018** [521xueweihan/GitHub520#101]
如果 设置 DNS封锁清单  是打不开的
是在 DNS允许清单里设置 才能打开
希望能修改下说明

**Comment by tony198911** [comment]
![image](https://user-images.githubusercontent.com/18481553/137129222-bd32f127-3e6a-4de2-89d7-ea6e030422d5.png)
实测放封锁清单里可以打开，作者强调的没错
