### ISSUE TITLE
Chrome 插件方式 装了插件之后反而访问不到github了。。。

### ISSUE THREAD

**Issue by honger1234** [521xueweihan/GitHub520#106]
我试了几次，装了反而上不了github，自己卸载之后又可以了，开始以为是跟host文件里配的github的ip冲突，删了host的配置也没用，有跟我一样情况的吗

**Comment by 521xueweihan** [comment]
应该是插件问题，这里不做讨论。
host更新地址：https://raw.hellogithub.com/hosts
