### ISSUE TITLE
为什么在windows电脑和centos上ping同一个ip地址，centos上ping不通

### ISSUE THREAD

**Issue by lovelyJason** [521xueweihan/GitHub520#117]
如题， 在windows电脑上和centos上都配置了这些hosts， 本地电脑可以ping通github和这些ip， 服务器里面ping不通

**Comment by lovelyJason** [comment]
貌似这个host在服务器不让用？

**Comment by Abeautifulsnow** [comment]
首先，你应该检测一下你的ping是否针对其他ip或者url可以ping通。
其次，如果ping没问题，那么你在服务器ping不通应该是受限于你的服务器所在网络。

在本地ping和在远端服务器ping，网络延迟是不同的。可能存在本地通，服务器不通，或者服务器通，本地不通的情况。
