### ISSUE TITLE
是否考虑加上ssh.github.com支持？

### ISSUE THREAD

**Issue by HansBug** [521xueweihan/GitHub520#118]
如题，实际上国内访问github常常会出现网页能上，ip能ping，但是ssh贼慢或干脆超时的其情况。

其中一个解决方式是[使用ssh.github.com](https://zhuanlan.zhihu.com/p/149288774)

因此可否考虑添加ssh.github.com的ip地址支持？以便同时确保ssh也可以不断更新最新ip。 😄

**Comment by mylovesaber** [comment]
看了下，好像跟这个项目没啥关系？

**Comment by HansBug** [comment]
有啊，就是希望加一行ssh.github.com的，方便使用。
