### ISSUE TITLE
2.2 自动方式 URL这里是填写 https://raw.hellogithub.com/hosts吗？

### ISSUE THREAD

**Issue by freejacklee** [521xueweihan/GitHub520#120]
2.2 自动方式
Tip：推荐 SwitchHosts 工具管理 hosts

以 SwitchHosts 为例，看一下怎么使用的，配置参考下面：

Title: 随意

Type: Remote

URL: https://raw.hellogithub.com/hosts

Auto Refresh: 最好选 1 hour

**Comment by 521xueweihan** [comment]
@freejacklee 是的

**Comment by freejacklee** [comment]
@521xueweihan 谢谢大佬~新年快乐
