### ISSUE TITLE
AD guard上没有找到过滤器啊

### ISSUE THREAD

**Issue by redleafnew** [521xueweihan/GitHub520#129]
在哪找过滤器，是设置中吗?
用户过滤器好像不对。

<img width="541" alt="msedge_Dg2qrr5jNH" src="https://user-images.githubusercontent.com/22135631/158044405-ec7c8c43-6ba5-42af-9e79-15128ab02438.png">
<img width="570" alt="msedge_rRt5RyVFEB" src="https://user-images.githubusercontent.com/22135631/158044406-3fc66610-2ea1-48cd-8fbc-0ede81b7d5ea.png">
<img width="241" alt="msedge_ZYRLuPb9J3" src="https://user-images.githubusercontent.com/22135631/158044408-d58ef8a0-41fb-45dd-9bc3-d240a1d14db3.png">

**Comment by redleafnew** [comment]
哦，是软件中不是AGUARD的浏览器插件是吧。

**Comment by redleafnew** [comment]
但安装了软件之后也没有找到：过滤器>DNS 封锁清单

**Comment by redleafnew** [comment]
我安装了home软件也没有这个功能，是这个软件没有这个模块了吗？

**Comment by 521xueweihan** [comment]
@redleafnew 这个软件我没过用，所以无法回答。

**Comment by Jandaes** [comment]
adguard home 版本: v0.107.7
过滤器-->DNS允许列表   


在在这里！拦截列表的会阻止打不开github，这个允许就行！readme的好像不对
