### ISSUE TITLE
chrome插件版怎么操作

### ISSUE THREAD

**Issue by mortal-94** [521xueweihan/GitHub520#135]
“将domain换成最快的那个“怎么操作啊？domain在哪里啊？

**Comment by TinkingLoeng** [comment]
我觉得这句话是在解释原理而不是步骤：“……主要原理是拦截浏览器的某些请求，将 domain 替换成访问速度较快的那个。……”

**Comment by mortal-94** [comment]
所以，按照这个方法应该怎么操作呢？小白不懂，请指教一下，谢谢😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [521xueweihan/GitHub520] chrome插件版怎么操作 (Issue #135)




 
我觉得这句话是在解释原理而不是步骤：“……主要原理是拦截浏览器的某些请求，将 domain 替换成访问速度较快的那个。……”
