### ISSUE TITLE
使用后还是经常打不开

### ISSUE THREAD

**Issue by fsnhljz** [521xueweihan/GitHub520#139]
也都是及时更新了，但还是会打不开，例如我现在好好地写着反馈，能流畅打开，但过一阵以后又不行了，这是什么原因呢？

**Comment by Cinnamoroll-Rabbit** [comment]
是的，我也是这样，必须不停的改hosts才行

**Comment by chazandrune** [comment]
有时候用了打不开，不用反而能打开还很快，就很奇怪

**Comment by MoeCinnamo** [comment]
> 有时候用了打不开，不用反而能打开还很快，就很奇怪

确实很奇怪，对于PC端来说，还是FastGithub项目更稳妥些；对于移动端，如果在没有ipv6的环境下可以尝试使用，如果有ipv6就提前用ipv6就可以。

**Comment by fsnhljz** [comment]
> > 有时候用了打不开，不用反而能打开还很快，就很奇怪
> 
> 确实很奇怪，对于PC端来说，还是FastGithub项目更稳妥些；对于移动端，如果在没有ipv6的环境下可以尝试使用，如果有ipv6就提前用ipv6就可以。

请教一下怎么用IPV6访问呢？有开通了，但搜索没具体方法
