### ISSUE TITLE
没有写入host权限

### ISSUE THREAD

**Issue by wuhlcom** [521xueweihan/GitHub520#140]
![image](https://user-images.githubusercontent.com/12484119/168516709-75db8b2b-6fd4-42e6-b3bc-68a52722c546.png)

**Comment by chazandrune** [comment]
到 `C:\Windows\System32\drivers\etc` 目录下找到`hosts`文件改下权限，右键——属性——安全选项卡，把`ALL APPLICATION PACKAGES`和`Users`两个用户组的权限加上“写入”就可以了。
![屏幕截图 2022-05-19 000834](https://user-images.githubusercontent.com/16676546/169090403-07dd5f2f-1504-4268-b468-fb2ef652b5c9.png)
