### ISSUE TITLE
请问大佬，ssh.github.com 这个host有吗，ssh最近一直连接不上，开机场也无法连接

### ISSUE THREAD

**Issue by cuikangyuan** [521xueweihan/GitHub520#141]
请问大佬，ssh.github.com 这个host有吗，ssh最近一直连接不上，开机场也无法连接
一直报下面的错误
ssh: connect to host ssh.github.com port 22: Connection refused

**Comment by tribleice** [comment]
同问，即便切换为443端口也是同样的情况
ssh: connect to host ssh.github.com port 443: Connection refused
虽然我尝试把网络换为手机热点好像就可以

**Comment by MoeCinnamo** [comment]
貌似用浏览器也打不开，不知道是网络问题还是官方给关了。可以试试修改hosts为 140.82.114.35,140.82.114.36,140.82.112.36,140.82.121.36,54.168.17.15,18.181.13.223,3.34.26.58 试试。这些ip我这都能ping通，不确定能用。

**Comment by cuikangyuan** [comment]
目前我每次是 使用网络工具 ping ssh.github.com，然后把ping通的ip添加到hosts，这种办法倒是可行

**Comment by 521xueweihan** [comment]
@cuikangyuan 得用终端代理 proxychains4
