### ISSUE TITLE
插件安装报错

### ISSUE THREAD

**Issue by xueyongfu** [521xueweihan/GitHub520#143]
![image](https://user-images.githubusercontent.com/48610386/171538873-5a2995a1-678a-4b4b-a0a2-523644953be7.png)
![image](https://user-images.githubusercontent.com/48610386/171539000-ac000e0e-d54e-4570-8fe7-b0c6440e5b3f.png)

**Comment by 521xueweihan** [comment]
插件问题，不在本项目的讨论范围之内哈
