### ISSUE TITLE
Adguard无法正确拦截GitHub请求

### ISSUE THREAD

**Issue by Miooiio** [521xueweihan/GitHub520#145]
![image](https://user-images.githubusercontent.com/107167205/173292373-5f3d07ab-a49f-4dc2-ae71-f5746bc79294.png)
我在2022/6/13 14：25解析objects.githubusercontent.com这个域名时，adguard没有在日志中返回正确ip，也没有向外转发，就没办法链接这个地址，我在服务器正确配置了dns，有的时候在请求GitHub时也没办法返回正确ip，后台也没有记录
![image](https://user-images.githubusercontent.com/107167205/173292560-039ac623-3a76-48b8-a3ef-9fc97a45fa24.png)

**Comment by 521xueweihan** [comment]
插件问题，不在本项目的讨论范围之内哈
