### ISSUE TITLE
Linux怎么配置？

### ISSUE THREAD

**Issue by caixc-code** [521xueweihan/GitHub520#151]

**Comment by bond-aspecta** [comment]
使用文档里提到的脚本一键操作: 
https://github.com/521xueweihan/GitHub520#23-one-liner-%E9%80%82%E7%94%A8%E4%BA%8E%E7%B1%BBunix%E7%B3%BB%E7%BB%9F

或手动打开 hosts 文件 `sudo vi /etc/hosts`, 把内容粘贴进去. 保存退出 `:wq`.

**Comment by taotieren** [comment]
systemd 的方式：https://github.com/521xueweihan/GitHub520/pull/212
