### ISSUE TITLE
访问GitHub网站样式丢失

### ISSUE THREAD

**Issue by LauGaHo** [521xueweihan/GitHub520#158]
最近通过SwitchHosts工具使用本项目的host配置会导致访问GitHub网站的样式丢失

**Comment by Abeautifulsnow** [comment]
尝试清空所有作出的代理配置。

我今天也遇到这个问题，所有 github.githubassets.com 域名下面的css样式、字体都爆红。然后我索性将代理的所有ip与域名配置删除，现在正常了😂

**Comment by laoma2016** [comment]
刚才测试了下直接打开github.githubassets.com下的css地址，显示被拒绝，估计这个站点有可能限制了国内的ip，我的是中国电信
