### ISSUE TITLE
我通过AdGuardHome 添加dns拦截列表  github 直接打不开了  取消后 才能打开 不知道是不是不该放到拦截列表

### ISSUE THREAD

**Issue by xingleiwu** [521xueweihan/GitHub520#159]
![image](https://user-images.githubusercontent.com/13015600/181275006-3da7402d-537d-4010-8b60-38b2e4dda5ad.png)

加上这个url   https://raw.hellogithub.com/hosts  网址直接被拦截了

**Comment by aoaim** [comment]
我也是同样情况

**Comment by casselluu** [comment]
adguard设置里，dns设置，拦截模式是默认的话就是按教程添加

**Comment by jiaotashidiyangwangxingkong** [comment]
> adguard设置里，dns设置，拦截模式是默认的话就是按教程添加

对的，在 设置 -》 DNS设置， 拦截模式勾选**默认**
>默认： 被 /etc/hosts 规则拦截时反应为规则中指定 IP 地址
