### ISSUE TITLE
缺失hosts映射：objects-origin.githubusercontent.com

### ISSUE THREAD

**Issue by fffguo** [521xueweihan/GitHub520#160]
objects-origin.githubusercontent.com

在发布release，上传文件会调用这个域名下的请求，没有该域名的host映射

![image](https://user-images.githubusercontent.com/27751972/182051485-402cf888-47f8-42e4-81eb-f23d73028342.png)
![image](https://user-images.githubusercontent.com/27751972/182051560-5b886c44-9411-45b6-88e5-35653850f060.png)

**Comment by mylovesaber** [comment]
那hosts规则中有一个objects开头的域名规则，你加一个同ip但域名是你这个的试试有效么？
