### ISSUE TITLE
依旧打不开...

### ISSUE THREAD

**Issue by LeoXiang2333** [521xueweihan/GitHub520#163]
没有用啊，在一个固定的IP打开过一次之后马上就被TCP阻断，要过一段时间才能打开，和不改hosts没有区别啊

**Comment by Pinghigh** [comment]
配上[fastgithub](https://github.com/dotnetcore/FastGithub/)这类sni阻断工具倒是效果不错
但是我用[dev-sidecar](https://github.com/docmirror/dev-sidecar)，它自带一个测速选择ip的功能
