### ISSUE TITLE
switchhosts 配置后，github加载不出图片，发现是github520图片相关的IP与我自己查询的IP不一致

### ISSUE THREAD

**Issue by liujinbo123** [521xueweihan/GitHub520#166]
github520 中图片相关的IP更新有问题，导致打开github，所有图片都加载不出来

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
