### ISSUE TITLE
switchhosts 按照操作配置后，github图片加载不出来，发现github520更新的图片相关IP不正确

### ISSUE THREAD

**Issue by liujinbo123** [521xueweihan/GitHub520#167]
switchhosts 按照操作配置后，github图片加载不出来，发现github520中更新出来的图片相关的IP，和我自己查询的IP不一致，所以无法加载出正确图片。希望作者及时修正一下。

**Comment by Huang131** [comment]
我也遇到了同样的问题，我停用github520后，将dns改成8.8.8.8，就可以访问了

**Comment by mxm646690173** [comment]
+1, 当 switchhosts 开启 github520 中的host 的时候, github的图片无法正确展示, 当关闭 github520 ,开启代理的时候, 图片能正确展示

**Comment by Nireil** [comment]
+1

**Comment by lrhan321** [comment]
+1  使用switchhosts 开启github520过后会无法加载图片

**Comment by gaofeiyang2022** [comment]
+1

**Comment by gaofeiyang2022** [comment]
3 开头的IP都不行
