### ISSUE TITLE
手动/自动方式都试了，全不管用，难道这种方法现在失灵了？

### ISSUE THREAD

**Issue by larsonzh** [521xueweihan/GitHub520#170]

**Comment by ZLD1819858** [comment]
前段时间搞Twenty Big会议的影响吧。

**Comment by larsonzh** [comment]
现在还是不行，不知别处是否可以。

**Comment by ZLD1819858** [comment]
唉，国内这墙真的无语，qtmd，还是得挂梯子。

**Comment by larsonzh** [comment]
不用这东东和梯子，时不常的倒是可以像现在这样直接访问GitHub，奇了怪了。

**Comment by iifly** [comment]
今天挂这个，加载出来的页面 CSS 完全没生效，就一个白板网页

**Comment by ZLD1819858** [comment]
始终找不到一个完美的访问github方案......还是连vpn稳定

**Comment by YSB123123123** [comment]
我也有这个问题，发现是github.githubassets.com的ip地址不对，手动获取后并修改hosts后可以正常访问
