### ISSUE TITLE
红彤彤的超时堆成山

### ISSUE THREAD

**Issue by Tinhone** [521xueweihan/GitHub520#172]
![图片](https://user-images.githubusercontent.com/81268244/202815454-ddf81e54-3cca-4d5d-a5ba-5c1514e48866.png)

**Comment by Tinhone** [comment]
![图片](https://user-images.githubusercontent.com/81268244/202815591-7154af81-288c-4f5b-b082-f537153a3987.png)

**Comment by 521xueweihan** [comment]
@Tinhone 问题已修复，请尝试最新的IP
