### ISSUE TITLE
更新的 IP 数量变少

### ISSUE THREAD

**Issue by PumpkinJui** [521xueweihan/GitHub520#173]
您好，以前更新的 IP 都是铺满一屏幕的，现在只能看到三两个，甚至连 github.com 域名的 IP 都不见了。请问这是什么情况？
另外，这个仓库是已经无人维护，只靠自动运行了吗？我很喜欢这个项目，希望它不要半路倒闭。

**Comment by 521xueweihan** [comment]
@PumpkinJui 收到，感谢您的支持，我今天就看

**Comment by 521xueweihan** [comment]
@PumpkinJui 感谢您的反馈，问题已修复。
