### ISSUE TITLE
a sub ip can not be linked

### ISSUE THREAD

**Issue by LIU0116** [521xueweihan/GitHub520#177]
this raw.githubusercontent.com ip can not be linke,

i have renew ip of raw.xxxueser.com form ip fond web, also renew ip in own computer

but the web can not be linked like before

how can i  sovle the problome

my pc is windows systeam.

**Comment by 521xueweihan** [comment]
@LIU0116  I update my code, Please use lastest hosts file and try again.
我更新了代码，下载最新的 hosts 文件，再试试看。

**Comment by LIU0116** [comment]
感谢！ 已经可以用了

发件人: ***@***.***>
发送时间: 2022年12月6日 22:06
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [521xueweihan/GitHub520] a sub ip can not be linked (Issue #177)


@LIU0116<https://github.com/LIU0116> I update my code, Please use lastest hosts file and try again.
我更新了代码，下载最新的 hosts 文件，再试试看。

―
