### ISSUE TITLE
增加 Copilot 的相关 ip

### ISSUE THREAD

**Issue by asakiasako** [521xueweihan/GitHub520#181]
希望在后续的更新中将相关的一些域名解析包括进去。谢谢！
例如：copilot-proxy.githubusercontent.com

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 521xueweihan** [comment]
@asakiasako 增添后测试发现，无可用 ip

**Comment by StreakingMan** [comment]
@521xueweihan 

dns checker是能查到的 [https://dnschecker.org/#A/copilot-proxy.githubusercontent.com](https://dnschecker.org/#A/copilot-proxy.githubusercontent.com)
