### ISSUE TITLE
想用这个功能添加其他域名的解析，能否出一个自建github action教程

### ISSUE THREAD

**Issue by mztian** [521xueweihan/GitHub520#182]
目前组装了个nas，刮削电影需要api.themoviedb.org，该网址不能自动解析
能否出个教程 自己添加网址的github action
小白一个
最后感谢大佬能提供github520这个项目

**Comment by 521xueweihan** [comment]
@mztian 
并不是所有的网站都可以通过指定 IP 搞定哈，
关于增加域名可以参考这里的改动：https://github.com/521xueweihan/GitHub520/commit/8a3b384690724a6da126dc16e63b6f0a90ee7c4c

Action 无需教程，直接 fork 本项目即可。
