### ISSUE TITLE
github.com跳转raw.githubusercontent.com使得host无效？

### ISSUE THREAD

**Issue by user-tq** [521xueweihan/GitHub520#184]
我在linux上使用conda安装软件有一个地址为```https://github.com/snakemake/snakemake-wrappers/raw/v1.22.0/bio/vep/cache/wrapper.py```
我已经修改host文件
但我还是无法访问
我尝试在自己的电脑访问发现，此地址会跳转？为```https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v1.22.0/bio/vep/cache/wrapper.py```
我推测是无法解析raw.githubusercontent.com/的原因，如何处理呢
![image](https://user-images.githubusercontent.com/72878144/223617238-2d864ab0-1a3d-4022-b3fc-09b8df04e67c.png)

**Comment by 521xueweihan** [comment]
@user-tq 列表不全的问题已修复，可以重新尝试。
