### ISSUE TITLE
[docs]README 中 sed 命令行参数报错

### ISSUE THREAD

**Issue by edonyzpc** [521xueweihan/GitHub520#185]
在 BSD/MacOS 中执行 README 中的 sed 命令行时 `sed -i "/# GitHub520 Host Start/Q" /etc/hosts` 有如下报错：
```
[edony@MacBook-Pro.local ~ :57]$
>> sed -i "/# GitHub520 Host Start/Q" /etc/hosts
sed: 1: "/etc/hosts": extra characters at the end of h command
```

错误原因应该是：
[BSD/MacOS 的 sed 和 GNU sed 命令行参数不一样](https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac)

[README 2.3](https://github.com/521xueweihan/GitHub520#23-%E4%B8%80%E8%A1%8C%E5%91%BD%E4%BB%A4-%E9%80%82%E7%94%A8%E4%BA%8E%E7%B1%BB-unix-%E7%B3%BB%E7%BB%9F) 增加 macOS/BSD sed 命令支持：

```sh
# for GNU sed (Ubuntu/CentOS/Fedora)
sed -i "/# GitHub520 Host Start/Q" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts

# for BSD/macOS sed
sed -i "" "/# GitHub520 Host Start/,/# Github520 Host End/d" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts
```

**Comment by 521xueweihan** [comment]
@edonyzpc 感谢贡献，已更新。
