### ISSUE TITLE
-bash: /etc/hosts: Permission denied

### ISSUE THREAD

**Issue by Zhonglu** [521xueweihan/GitHub520#191]
你好，

在WSL ubuntu20.04 中使用如下命令：
`sudo sed -i "/# GitHub520 Host Start/Q" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts`

提示错误：
`-bash: /etc/hosts: Permission denied`

祝
好

**Comment by cxwx** [comment]
Permission denied
```
sudo  sed -i .....
```

**Comment by Zhonglu** [comment]
sudo 之后仍然 permission denied，以上是sudo后的结果

**Comment by LQYHYQ** [comment]
先`su root`，切换到root用户下，再执行命令`sed -i "/# GitHub520 Host Start/Q" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts`就可以了

**Comment by Zhonglu** [comment]
可以了 多谢！

**Comment by taotieren** [comment]
可以使用 systemd 方式来管理：https://github.com/521xueweihan/GitHub520/pull/212
