### ISSUE TITLE
Linux中使用  提示权限不够的解决办法

### ISSUE THREAD

**Issue by zheng7fu2** [521xueweihan/GitHub520#197]
sudo sed -i "/# GitHub520 Host Start/Q" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts
提示权限不够 : /etc/hosts 

上网查询找到解决办法：
https://blog.csdn.net/change_can/article/details/115128218

sudo  sh -c 'sed -i "/# GitHub520 Host Start/Q" /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts'

**Comment by xiatian12345** [comment]
权限不够的问题确实可以解决，但是这个方法不能和crontab配合使用啊，定时任务怎么能解决输入密码的问题呢

**Comment by taotieren** [comment]
我在 systemd 中增加了 root 权限的处理，可以参考这种方式 https://github.com/521xueweihan/GitHub520/pull/212
