### ISSUE TITLE
cron定时任务权限问题

### ISSUE THREAD

**Issue by xiatian12345** [521xueweihan/GitHub520#198]
sed -i '' '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts
提示权限不够 sed: /etc/hosts: Permission denied
使用sudo bash -c "sed -i '' '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/hosts && curl https://raw.hellogithub.com/hosts >> /etc/hosts"通过输入密码可以解决权限的问题
但是配合cron定时任务的时候怎么解决权限问题呀，定时任务怎么能输入密码呢？

**Comment by 521xueweihan** [comment]
@xiatian12345 问题已修复，请查看最新的 README
