### ISSUE TITLE
大牛可以给*.github.io的地址吗

### ISSUE THREAD

**Issue by fanbitian** [521xueweihan/GitHub520#20]
配置了host之后，之前裂开的图片现在可以加载出来了。但是*.github.io的地址还是不能访问，可以加上这个地址的ip吗

**Comment by 521xueweihan** [comment]
好的，我有时间搞。

**Comment by 521xueweihan** [comment]
@fanbitian 你好 hosts 文件不支持泛域名，所以不能通过修改 hosts 来支持 *.github.io

我增加了 github.io 的域名解析，不知道有没有用。我尽力啦！

**Comment by SamLukeYes** [comment]
目前阿里的 DNS 服务器可以正常解析 GitHub Pages 的域名，把你的 DNS 设置为 223.5.5.5 即可，或者用 dnsmasq 等手段设置用 223.5.5.5 解析以 github.io 结尾的域名
