### ISSUE TITLE
linux更新了hosts，但是没有效果。没有代理无法访问github

### ISSUE THREAD

**Issue by fengyunzaidushi** [521xueweihan/GitHub520#200]
系统：linux
更新了hosts，但是没有效果。没有代理无法访问github
电脑也重启了。
![image](https://github.com/521xueweihan/GitHub520/assets/53250064/c62ecd35-88a9-459f-a2b8-8b00aff38e35)

**Comment by 521xueweihan** [comment]
@fengyunzaidushi 目标网站改版，问题已修复。
