### ISSUE TITLE
https://gist.github.com/ 无法访问

### ISSUE THREAD

**Issue by 91xcode** [521xueweihan/GitHub520#201]
https://gist.github.com/ 无法访问  提示 无法访问此网站 连接已重置。

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 521xueweihan** [comment]
@91xcode 登陆状态下试试
