### ISSUE TITLE
只有v4吗？

### ISSUE THREAD

**Issue by Hello-XPH** [521xueweihan/GitHub520#204]
只有v4吗？

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 521xueweihan** [comment]
@Hello-XPH 是的

**Comment by Hello-XPH** [comment]
没有打算支持一下ipv6吗？

**Comment by hm9245** [comment]
> 没有打算支持一下ipv6吗？

GitHub主站（指的是github.com，包括其子域名）都没有v6的服务器，没法适配

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hello-XPH** [comment]
明白了，谢谢
