### ISSUE TITLE
为啥更换了host后比我本地还有慢，本地有时会卡的打不开github

### ISSUE THREAD

**Issue by whenStoneHaveLove** [521xueweihan/GitHub520#207]
本地有时快有时慢，有时卡的打不开，想问一下你这个host是最优的吗，图片上面是没有host的，下面是绑host的。
![image](https://github.com/521xueweihan/GitHub520/assets/28730556/efebb6fb-1fb8-413a-9613-0c59b5171b21)

**Comment by sandaisi** [comment]
我的情况和你一样

**Comment by 521xueweihan** [comment]
@whenStoneHaveLove 可以试试自动替换 host
