### ISSUE TITLE
MacOS App Gas Mask download error: Bad content Can't download the hosts file. It contains HTML page

### ISSUE THREAD

**Issue by laris** [521xueweihan/GitHub520#208]
MacOS App Gas Mask download error: Bad content Can't download the hosts file. It contains HTML page

Must open in browser to download hosts file.

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
