### ISSUE TITLE
更换hosts后访问GitHub图片还是加载不出来

### ISSUE THREAD

**Issue by Mubai-meng** [521xueweihan/GitHub520#209]
下载东西也下不动
![Screenshot_2023-11-22-09-44-33-016_com.github.android.jpg](https://github.com/521xueweihan/GitHub520/assets/86759349/a5ac616d-ed2c-4218-94ee-2e36b6b1cda5)

**Comment by xuehaoweng** [comment]
俺也一样

**Comment by songyunbiao** [comment]
头像确实加载不出来，访问也有点慢。

**Comment by 521xueweihan** [comment]
我找时间看看，可能是图片的 hosts 没在列表里。
