### ISSUE TITLE
Debian用户1配置了这个host，使用正常。创建用户2的时候再wget之类会出错

### ISSUE THREAD

**Issue by jaytai** [521xueweihan/GitHub520#210]
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... connected.
WARNING: The certificate of 'raw.githubusercontent.com' is not trusted.
WARNING: The certificate of 'raw.githubusercontent.com' doesn't have a known issuer.
The certificate's owner does not match hostname 'raw.githubusercontent.com'
HTTP request sent, awaiting response... 404 Not Found

像上面这个，这个应该如何解决，求教~！

**Comment by taotieren** [comment]
使用 systemd 这个方式试试：https://github.com/521xueweihan/GitHub520/pull/212
