### ISSUE TITLE
换了这个仓库里的 hosts 之后更连不上了

### ISSUE THREAD

**Issue by MechCrafter** [521xueweihan/GitHub520#214]
我用了这个仓库里的 hosts 文件之后反而不能连接 GitHub 了，我这儿开 steam++ 是可以直连 GitHub 的，只是不能推送到 GitHub 和拉取 GitHub 仓库，所以才找到这个仓库里的 hosts 文件，结果起了反效果，连 GitHub 都不能上了（同样也开了 steam++），我在知乎找到一个[hosts](https://zhuanlan.zhihu.com/p/107334179)，用这个 hosts 就可以推送和拉取了，前提是开了 steam++ 和用了知乎的 hosts 文件，steam++ 版本是 `x64 v2.8.6 for Windows`，亲测有效，只是每次开机要手动把 hosts 文件替换为知乎的那个，直接在 hosts 文件下面加上就可以了，不需要把原本的删除

**Comment by hm9245** [comment]
但我粗略对比了一下，这两个hosts差不多a

**Comment by Petricho0r** [comment]
> 但我粗略对比了一下，这两个hosts差不多a

我这边可以用，不知道那边为什么不能用

**Comment by glue208** [comment]
试试 https://github.com/glue208/github-hosts 不用改hosts

**Comment by githubfat** [comment]
> 我用了这个仓库里的 hosts 文件之后反而不能连接 GitHub 了，我这儿开 steam++ 是可以直连 GitHub 的，只是不能推送到 GitHub 和拉取 GitHub 仓库，所以才找到这个仓库里的 hosts 文件，结果起了反效果，连 GitHub 都不能上了（同样也开了 steam++），我在知乎找到一个[hosts](https://zhuanlan.zhihu.com/p/107334179)，用这个 hosts 就可以推送和拉取了，前提是开了 steam++ 和用了知乎的 hosts 文件，steam++ 版本是 `x64 v2.8.6 for Windows`，亲测有效，只是每次开机要手动把 hosts 文件替换为知乎的那个，直接在 hosts 文件下面加上就可以了，不需要把原本的删除

确实，我前天刚部署了adguardhome方式，测试了两天，发现如你所说。

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
