### ISSUE TITLE
请问一下，为什么该hosts指定的是美国服务器，而不是新加坡服务器？

### ISSUE THREAD

**Issue by haoming9245** [521xueweihan/GitHub520#215]
RT，单纯地问一下，新加坡服务器也没被墙a，为什么不用

**Comment by dwing4g** [comment]
其实目前墙不是按IP墙的, 而是通过SNI阻断, 只要访问这个域名, 哪个IP都会墙. 只是目前不是100%阻断, 特殊时期会调节阻断率.

**Comment by bond-aspecta** [comment]
@hm9245  我觉得没必要, 毕竟服务器还是在美国罢, 直连就好, 去趟新加坡总时长会更大应该.

**Comment by 521xueweihan** [comment]
@haoming9245 hk 服务器测速的结果
