### ISSUE TITLE
真的要挂梯子才上得去了

### ISSUE THREAD

**Issue by oldeightLB** [521xueweihan/GitHub520#219]
<img width="1080" alt="image" src="https://github.com/521xueweihan/GitHub520/assets/109260128/659ddde8-843e-4ba7-ad71-33407f41408c">

**Comment by oldeightLB** [comment]
然后我改了hosts，又上来了

**Comment by oldeightLB** [comment]
现在我不用挂梯子了

**Comment by Mubai-meng** [comment]
求个你图中的网页链接
