### ISSUE TITLE
修改的host之后，下载文件非常慢

### ISSUE THREAD

**Issue by 1357214904** [521xueweihan/GitHub520#22]
比如说下载你推荐的软件，我是直接用迅雷下的，3.0k/b的速度。
看下有没有优化的可能
https://github.com/oldj/SwitchHosts/releases

**Comment by 521xueweihan** [comment]
这个我研究下。

**Comment by 521xueweihan** [comment]
@1357214904 您好，我研究了下。release 下载是通过 amazonaws s3 存储下载资源。

然后这个 s3 地址并不固定，所以需要支持泛域名，但是 hosts 不支持泛域名。暂时不能提速

**Comment by XIU2** [comment]
@521xueweihan  
Github Releases 的域名是固定的：`github-production-release-asset-2e65be.s3.amazonaws.com`  
Github 亚马逊 s3 相关的域名一共有：
```
github-production-release-asset-2e65be.s3.amazonaws.com
github-production-user-asset-6210df.s3.amazonaws.com
github-cloud.s3.amazonaws.com
github-com.s3.amazonaws.com
github-production-repository-file-5c1aeb.s3.amazonaws.com
```

另外，你还少添加了个域名：`codeload.github.com` 这个域名是源码ZIP打包下载时的域名。

**Comment by 521xueweihan** [comment]
@XIU2 感谢。加上了

**Comment by SamLukeYes** [comment]
我这边 GihHub releases 的下载地址会跳转到 github-releases.githubusercontent.com，下载速度有时会非常慢

**Comment by XIU2** [comment]
@SamLukeYes 

你这个回复提醒了我，我跑这里“发广告”来啦！

看下我刚发的 #47 用油猴脚本来解决 Github 各种文件下载速度慢的问题。

**Comment by SamLukeYes** [comment]
@XIU2 油猴脚本我也用，但并不能满足我的所有需求。比如说我的内核更新是由 linux-surface 仓库提供的，这个仓库的下载是直接重定向到 GitHub releases 的 (https://github.com/linux-surface/linux-surface/issues/303#issuecomment-707409078)。如果不解决从 GitHub 下载慢的问题，每次有内核更新的时候就需要手动访问 GitHub releases，点击油猴脚本提供的下载按钮，再手动安装，才能进行其他的更新，否则就会直接把 `pacman -Syu` 卡在半路。

**Comment by XIU2** [comment]
@SamLukeYes 

可问题是，Github 的 Releases 文件下载域名只有亚马逊的美国服务器，无论怎么改 Hosts 都是美国服务器，对下载速度提升很有限。

**Comment by XIU2** [comment]
@SamLukeYes 

像你这种比较特殊的需求：
- 要么就是**挂梯子**，
- 要么就是**国外服务器上建个 SNI 服务器**，然后改下 Hosts 指向该服务器 IP。
_只要你访问这个国外服务器速度比亚马逊美国服务器快就行了。_

**Comment by SamLukeYes** [comment]
> @SamLukeYes
> 
> 可问题是 Github 的 Releases 文件下载只有亚马逊的**美国服务器**，无论怎么改 Hosts 都是美国服务器，对**下载速度提升很有限**。

刚才试了一下用 9.9.9.9 解析 github 的域名，下载速度挺快的，不知道换个时间还快不快
