### ISSUE TITLE
【建议】增加hub.docker.com的地址信息

### ISSUE THREAD

**Issue by kermitbu** [521xueweihan/GitHub520#220]
建议增加hub.docker.com的地址信息

**Comment by M1s4k1** [comment]
附议

**Comment by xuxiaocheng0201** [comment]
同求

**Comment by silascript** [comment]
好像没用吧。hub.docker是docker方面墙中国，好像是被列入实体清单了。而且如果只是「pull」docker的镜像，国内不是有一堆的镜像站可用。如果是查询，那只能靠网易提供的接口去弄个查询脚本了--能免费公开用的docker hub 按查询tag的接口的好像只有网易，网易真是业界良心！

**Comment by des0315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chengnan049** [comment]
那就是另一个项目的事儿了，一大堆镜像站呢

**Comment by Xihihhh** [comment]
> 好像没用吧。hub.docker是docker方面墙中国，好像是被列入实体清单了。而且如果只是「pull」docker的镜像，国内不是有一堆的镜像站可用。如果是查询，那只能靠网易提供的接口去弄个查询脚本了--能免费公开用的docker hub 按查询tag的接口的好像只有网易，网易真是业界良心！

最近还能DoH+域前置访问，这么快就docker方面墙了？那为啥他们还提供docker.com呢？🤔

加在这项目确实没用，因为若还只是防火墙方面墙的话，必有SNI阻断。

**Comment by wcy666103** [comment]
现在镜像不是都让下架了吗，怎么搞
