### ISSUE TITLE
未知原因无法加速

### ISSUE THREAD

**Issue by HenryJi529** [521xueweihan/GitHub520#25]
<img width="802" alt="Screenshot 2020-11-01 at 10 23 28" src="https://user-images.githubusercontent.com/41288155/97793834-495e7d00-1c2c-11eb-8a25-79054ce531d1.png">
<img width="807" alt="Screenshot 2020-11-01 at 10 23 38" src="https://user-images.githubusercontent.com/41288155/97793840-4f545e00-1c2c-11eb-8a59-e552a990c0c2.png">
mac平台
使用了SwitchHost客户端并添加了远程更新
依旧没能加速，想请教下原因

**Comment by Oshibuki** [comment]
用http协议下载

**Comment by HenryJi529** [comment]
还是不行～

**Comment by 521xueweihan** [comment]
@HenryJi529  下 zip 包
