### ISSUE TITLE
提供的动态 host 错误，github.com 被解析到了 127.0.0.1

### ISSUE THREAD

**Issue by itszhengkun** [521xueweihan/GitHub520#265]
<img width="1320" alt="image" src="https://github.com/user-attachments/assets/6222c85b-c32f-453d-8444-ffadf82334ee" />

**Comment by lovebai** [comment]
![image](https://github.com/user-attachments/assets/4f0f4268-ce44-4ff0-82f5-854f2e75487a)
我就说嘛 怎么挂梯都访问不了了

**Comment by Similarityoung** [comment]
+1

**Comment by 521xueweihan** [comment]
修复了
