### ISSUE TITLE
SwitchHosts本地与github520组合方案的问题

### ISSUE THREAD

**Issue by menkoudetieshu** [521xueweihan/GitHub520#28]
您好：

想问按您的教程配置好github520（联网）后与原有的hosts（本地）做一个组合方案，不勾选github520，勾选组合方案，github的hosts还会自动更新吗

![1213](https://user-images.githubusercontent.com/64588679/102968551-04b9d880-452f-11eb-9bdc-1706411fa954.png)
![1214](https://user-images.githubusercontent.com/64588679/102968558-097e8c80-452f-11eb-9f0f-d17018d4b79c.png)
![1215](https://user-images.githubusercontent.com/64588679/102968651-39c62b00-452f-11eb-85dc-42832ac51e71.png)

**Comment by 521xueweihan** [comment]
我不用 SwitchHosts 你可以自己观察一下。
