### ISSUE TITLE
项目图片比较多，如何能让其他人在看项目的时候不出现图裂问题

### ISSUE THREAD

**Issue by Alinlinlinlin** [521xueweihan/GitHub520#30]
您好，根据您提供的方法自己在使用github时图片可正常显示，想问下图裂问题是每个人都会遇到的吗？但是我的项目图片比较多，如果这样会大大影响其他人阅读的体验，请问有什么方法能使图片在他人阅读时正常显示？

**Comment by 521xueweihan** [comment]
放个链接，说明图裂了的话，就让他用我这个项目。

上面是开个玩笑，你可以试试图床。但是我 GitHub 的图片现在都是缓存在 GitHub 上，大概率无法解决。

**Comment by Alinlinlinlin** [comment]
非常感谢，我试一试：）
