### ISSUE TITLE
gitee 404

### ISSUE THREAD

**Issue by goldenfreemanchina** [521xueweihan/GitHub520#33]
gitee的hosts404了；

**Comment by 521xueweihan** [comment]
我刚把 gitee 上账户升级为组织了，升级完发现组织的 gist 不支持公开，只能私有！

导致了这次的问题，正在沟通解决。

**Comment by heyzqq** [comment]
> 我刚把 gitee 上账户升级为组织了，升级完发现组织的 gist 不支持公开，只能私有！
> 
> 导致了这次的问题，正在沟通解决。
> 
> 可以先用：https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts 这个链接顶一下

用了挺久的了，感谢，支持一下！

**Comment by 521xueweihan** [comment]
我问过 gitee 的客服了，回复如下：

gitee 代码片段的公开功能已经下线。

最新的 host 地址访问，所以会出现 404，现在已经该回到 github：https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

**Comment by heyzqq** [comment]
> 我问过 gitee 的客服了，回复如下：
> 
> gitee 代码片段的公开功能已经下线。
> 
> 最新的 host 地址访问，所以会出现 404，现在已经该回到 github：https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

这个链接访问不了，需要先把 readme 里能用的拿来手动设置一下 hosts，然后再连这个链接更新。
（估计下次失效了还得手动更新）
