### ISSUE TITLE
switchhost配置后无效

### ISSUE THREAD

**Issue by lijyze** [521xueweihan/GitHub520#34]
使用全局梯子，根据图片配置后。
关闭梯子仍然裂图。
我是遗漏了某些操作设置吗？

![image](https://user-images.githubusercontent.com/26381964/104811030-bcdb5800-5833-11eb-8d39-568582a49834.png)

![image](https://user-images.githubusercontent.com/26381964/104811040-cbc20a80-5833-11eb-8e65-1f79c5aa6af2.png)

**Comment by 521xueweihan** [comment]
我看你的截图感觉是 host 没有更新成功，我提供的那个host 文件的地址是 github 的可能不大好，之前 gitee 的地址很好用，当时现在改平台不提供支持了，我后面写个接口吧。这个issues不关，后面我弄好会在这里通知大家的。

**Comment by HerbertHe** [comment]
> 我看你的截图感觉是 host 没有更新成功，我提供的那个host 文件的地址是 github 的可能不大好，之前 gitee 的地址很好用，当时现在改平台不提供支持了，我后面写个接口吧。这个issues不关，后面我弄好会在这里通知大家的。

应该是url的问题, 因为url本身就是访问不了的, 可以把url考虑改成cdn的

`https://cdn.jsdelivr.net/gh/521xueweihan/GitHub520@main/hosts`

**Comment by HerbertHe** [comment]
已 [PR](https://github.com/521xueweihan/GitHub520/pull/36)
