### ISSUE TITLE
感觉作业创作思路有问题

### ISSUE THREAD

**Issue by baixf-xyz** [521xueweihan/GitHub520#35]
guthub小白,有什么说得不对的还希望大家谅解指正。
github actions 是自动服务，是在非本机环境下跑的程序，作者python文件只是测出了在那个环境下访问各个目的网址的最快ip,并不是我们本机访问这些网址的最快ip。
不知道我理解的是否有问题，理解有错的话还希望谅解指正。

**Comment by wayne0926** [comment]
嗯，但是不知为啥本地运行得到的内容是一样的

**Comment by wayne0926** [comment]
貌似源码思路不是这样的

**Comment by baixf-xyz** [comment]
是不是它在模拟本地登录？但是这个action并没有一个让我们添加secret，本地相关IP的参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "时过境迁Wayne"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上11:20
收件人: "521xueweihan/GitHub520"<GitHub520@noreply.github.com&gt;; 
抄送: "707401057"<707401057@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [521xueweihan/GitHub520] 感觉作业创作思路有问题 (#35)





 
貌似源码思路不是这样的

**Comment by wayne0926** [comment]
https://github.com/521xueweihan/GitHub520/blob/bb4d7ca166223cbecc8fd719bbec7d2cfb27f160/fetch_ips.py#L47

**Comment by wayne0926** [comment]
直接用那种查IP网站的结果，并非测速

**Comment by baixf-xyz** [comment]
ok 谢谢 我一会再看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "时过境迁Wayne"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上11:25
收件人: "521xueweihan/GitHub520"<GitHub520@noreply.github.com&gt;; 
抄送: "707401057"<707401057@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [521xueweihan/GitHub520] 感觉作业创作思路有问题 (#35)





 
直接用那种查IP网站的结果，并非测速

**Comment by wayne0926** [comment]
所以作者py可以说是定时爬取吧

**Comment by baixf-xyz** [comment]
对对 用的github action自动化




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "时过境迁Wayne"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上11:30
收件人: "521xueweihan/GitHub520"<GitHub520@noreply.github.com&gt;; 
抄送: "707401057"<707401057@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [521xueweihan/GitHub520] 感觉作业创作思路有问题 (#35)





 
所以作者py可以说是定时爬取吧

**Comment by 521xueweihan** [comment]
@baixf-xyz 小白可以直接用 action 跑出的结果，精准适配可以clone到本地手动跑
