### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by huoher** [521xueweihan/GitHub520#37]
由于Github的更新，建议您的Python文件URL中加入``avatars.githubusercontent.com``的扫描，以便更方便的显示图片
非常感谢您的作品，一直在用

**Comment by JeremySun1224** [comment]
Python文件的URL？请问具体怎么操作呢？

**Comment by huoher** [comment]
个人愚见，还请参考
在项目根目录的``fetch_ips.py``文件中，``RAW_URL``变量定义了许多链接，加入``avatars.githubusercontent.com``

**Comment by 521xueweihan** [comment]
有人提了个 PR 解决了
