### ISSUE TITLE
在此提供一个Windows下自动更新此项目中github的hosts内容的py脚本

### ISSUE THREAD

**Issue by chenyanzz** [521xueweihan/GitHub520#38]
如题，自己写了个py脚本，刷新hosts文件与此项目中内容匹配，
[gh@chenyanzz.hosts_add_github](https://github.com/chenyanzz/hosts_add_github)

**Comment by SamLukeYes** [comment]
我创建了一个跨平台的 fork：https://github.com/SamLukeYes/hosts_add_github

**Comment by zu1k** [comment]
用Rust写了一个， https://github.com/zu1k/github-hosts

**Comment by 521xueweihan** [comment]
我最初做这个项目的本意是：不需要安装软件就可以帮助访问 GitHub。

所以，本于本地自动更新的 hosts 的功能，可以参考 README 中 SwitchHost 工具（其他人提交的 PR）。
