### ISSUE TITLE
hosts url 好像要翻墙才可以访问吧,打不开这个链接比较麻烦

### ISSUE THREAD

**Issue by yyman001** [521xueweihan/GitHub520#4]
hosts url 好像要翻墙才可以访问吧,打不开这个链接比较麻烦, 要是有国内不用翻墙的就好了
https://raw.githubusercontent.com/521xueweihan/GitHub520/master/hosts

**Comment by 521xueweihan** [comment]
嗯，这个问题，我抽时间改一下

**Comment by CNFeffery** [comment]
> 嗯，这个问题，我抽时间改一下

可以在码云也托管一份一样的仓库

**Comment by 521xueweihan** [comment]
@yyman001 @CNFeffery 
gitee gitst 自动更新的订阅地址：https://gitee.com/xueweihan/codes/6g793pm2k1hacwfbyesl464/raw?blob_name=GitHub520.yml

**Comment by XIU2** [comment]
@521xueweihan 你其实可以用 `cdn.jsdelivr.net` 的 Github 项目反代，这个 CDN 是有国内服务器的，比 Gitee 都快。  
README.md 里的链接可以改成下面这个：  
https://cdn.jsdelivr.net/gh/521xueweihan/GitHub520/hosts

> 缺点是这类公共反代都有缓存，不过几个小时影响不大。
