### ISSUE TITLE
Chrome 使用安全 DNS 解决 DNS 污染

### ISSUE THREAD

**Issue by MHuiG** [521xueweihan/GitHub520#52]
## 使用安全 DNS 解决 DNS 污染

![image](https://user-images.githubusercontent.com/38281581/109454554-72363800-7a8f-11eb-9f29-6619ec44887d.png)

https://dns.alidns.com/dns-query

https://cloudflare-dns.com/dns-query

https://dns.google/dns-query

https://doh.pub/dns-query

https://dns.rubyfish.cn/dns-query

## SSH

> git push 建议使用 ssh

## 伪造的 SNI

https://github.com/SeaHOH/GotoX/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E4%BC%AA%E9%80%A0-SNI-%E7%9A%84%E5%8A%9F%E8%83%BD

**Comment by 521xueweihan** [comment]
有兴趣就提个不需要修改 host 的方案 pr 到 REAMDE_tempalte 文件

**Comment by wangping1511** [comment]
Safari有法子吗？

**Comment by diaosiqz** [comment]
现在都是SNI RST了吧

**Comment by leland17** [comment]
> ## 使用安全 DNS 解决 DNS 污染
> ![image](https://user-images.githubusercontent.com/38281581/109454554-72363800-7a8f-11eb-9f29-6619ec44887d.png)
> 
> https://dns.alidns.com/dns-query
> 
> https://cloudflare-dns.com/dns-query
> 
> https://dns.google/dns-query
> 
> https://doh.pub/dns-query
> 
> https://dns.rubyfish.cn/dns-query
> 
> ## SSH
> > git push 建议使用 ssh
> 
> ## 伪造的 SNI
> https://github.com/SeaHOH/GotoX/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E4%BC%AA%E9%80%A0-SNI-%E7%9A%84%E5%8A%9F%E8%83%BD

感觉有时候还是不稳定，就是打不开啊
