### ISSUE TITLE
Github.com 域名(hosts)指向任意 IP 就会出现 TCPing IP 443 端口超时 3 分钟。

### ISSUE THREAD

**Issue by XIU2** [521xueweihan/GitHub520#53]
# 本贴仅为学习交流，希望大家不要跑题~

# 起因

从前几天开始，我发现 Github 总是**频繁无法访问**（直连），而我这么多年**很少遇到这种情况**。

稍微注意了下，发现竟然**有规律**，于是花了一下午时间不停测试，得出了一些**不成熟**的结论。

****

# 复现

> **测试环境**：Windows10（联通家庭宽带）、Android 手机（联通 4G）

一开始我是拿了一些 `github.com` 的 IP 放在 Hosts 文件中轮番指向 `github.com` 来测试。

一旦指向后去访问 Github，就会发现这个 IP 的 **443 端口会超时**（TCPing），然后浏览器提示超时。

如果我关闭网页（避免浏览器一直重试），**等 3 分钟后**（TCPing 超时 90 次，超时时间 2 秒）443 端口就通了。

> 在此期间，该 IP 的 80 端口和 ICMP Ping 是一直正常通顺的，只有 443 端口超时。  

> 在此期间，整个局域网下全都 443 超时（准确说是整个宽带网络下），而独立的手机 4G 网络 TCPing 443 正常（包括其他在线端口测试网站也都 443 正常，国外更不用说了一切正常）。  

> 在此期间，对该 IP 进行 TCP 路由追踪时，会在出口处完全中断。

****

看到这里，其实就发现不对劲了，于是我又尝试**手机共享流量数据网络给电脑**，同样可以复现。

这时候，因为手机和电脑在同一个局域网（流量数据网络）下，所以也都 443 超时的。

****

# 进阶

测着侧着，突发奇想如果**指向其他非 Github 的 IP** 会怎么样？

于是我就找了个能用的 Cloudflare CDN IP（只要 443 端口可以 TCPing 就行）指向 Github 后，发现**也会出现 443 端口超时**的情况。。。

我也尝试过把 Github 的 IP 指向其他域名，结果**一切正常**，没有出现类似情况，只是针对 Github。

****

# 其他机制

因为持续测试了好几个小时的原因，还发现了一些其他机制：

## 触发时间/超时时间

有时候是一旦触发条件，就会直接超时 3 分钟（TCPing 超时 90 次，超时时间 2 秒），期间完全超时。

而有的时候是这 3 分钟期间还会漏掉一些正常延迟的 TCPing 结果，但经过测试依然无法访问网页，应该是**模拟丢包**。

而有的时候触发条件后，如果立即停止访问 Github，则就会发现 443 端口**不再超时**了。而如果一直不停的重试网页，那么超时时间就会无限长（重置为 3 分钟），这时候再去停止重试网页，超时时间就固定为 3 分钟了。

## 随机/轮番针对

有意思的是，似乎是随机或轮番针对 Github IP 的。

因为我发现有时候 IP A 在某一段时间内是可以**正常访问**的，相应其他的 IP B C D 等这段时间就会**无法使用**（一旦访问就 443 超时）。而过一段时间 IP A 又无法访问了，但又有另一个 IP B 可以正常访问了（顺序没有发现规律）。

也就是说，在**任意时间总有一个（或几个） IP 是可以正常访问**的，且不停变换。

****

目前为止，我只在我的**联通宽带+联通 4G 网络**下可以稳定复现，不清楚其他地区、运营商是否也一样。

欢迎大家测试、交流、分析。

**Comment by dwing4g** [comment]
电信和移动也是一样的, 所有的出口都使用了相同的策略.
应该是识别了TLS首个握手包里的host域名是否在黑名单, 在的话就把IP加入丢包黑名单几分钟.
但这个操作是异步的, 也就是识别出来的那个连接仍然有效直到断开. 所以症状就是有时能打开, 有时打不开.
另外, 不太清楚IP加入黑名单是针对所有来源还是特定IP的来源, 针对所有来源的话, 那连接成功率就小多了, 也可能是IP黑名单数量有限, 加入太多会把旧立即解封, 所以就有了"任意时间总有一个（或几个） IP 是可以正常访问"的现象.

**Comment by XIU2** [comment]
@dwing4g 

目前我测试的结果是，任意 IP 指向 Github 访问，都会 443 端口超时。
哪怕这个 IP 和 Github 无关（比如 Cloudflare CDN IP，只要 443 端口通顺，就可以拿来测试）。

经过测试是可以精细到共享同一个宽带 IP 的 NAT 用户下（也就是没有公网 IP）。
即该 IP 的 443 端口超时后，只会影响你自己的宽带，不会影响和你共享公网 IP 的 NAT 下其他宽带用户。

****

我认为之所以不完全封死，而是时能访问时不能（这个是因为 DNS 解析结果一直在变化，不能访问的时候说明解析到了无法使用的 IP，能访问的时候说明解析到了暂时可用的 IP），主要是为了模拟丢包、伪装成 Github 网站自身网络问题，这种方法对不懂技术的网民很有效，它们没有能力分辨。

而有能力分辨的人，也都有科学上网手段，遇到 Github 无法访问的问题，都会去配置其走代理。

****

要知道**当年 Github 被封**的时候，可是大量程序员反抗才恢复的。
而现在没什么人会去反抗了，反而只会去说：**你没有梯子吗？你不会挂代理吗？**之类的话。

看来**温水煮青蛙**策略很成功~

**Comment by dwing4g** [comment]
> 即该 IP 的 443 端口超时后，只会影响你自己的宽带，不会影响和你共享公网 IP 的 NAT 下其他宽带用户。
我写了个工具去测试github解析出来的一些IP, 发现确实是总有一部分能连, 一部分不能连, 即使好长时间没连过github也是如此. NAT在外面并不能分辨来源吧, 服务器只能看到一个IP从不同端口发来握手包, 但并不能分辨出哪些端口是同一终端发来的.

最近的策略好像有些变化了, 识别出握手包并不会很快把该IP加入黑名单, 已经无法识别出加入黑名单的时机了, 也无法确定解除黑名单的时机. 唯一能确定的是总有能访问的一些IP, 也总有一定丢包的一些IP, 变化的也很频繁, 目前访问率在一半左右. 但幸好只要握手成功, 那么该连接断开之前都能很流畅地上下行. 所以用浏览器打开的话, 只要页面打开了, 一段时间内重用该连接就一直能浏览下去.

很明显是在温水煮青蛙了. 十四五规划里有开源建设, 说明是打算捧国内的平台了, 同时逐步弱化github.

**Comment by crazyair** [comment]
> > 即该 IP 的 443 端口超时后，只会影响你自己的宽带，不会影响和你共享公网 IP 的 NAT 下其他宽带用户。
> 
> 我写了个工具去测试github解析出来的一些IP, 发现确实是总有一部分能连, 一部分不能连, 即使好长时间没连过github也是如此. NAT在外面并不能分辨来源吧, 服务器只能看到一个IP从不同端口发来握手包, 但并不能分辨出哪些端口是同一终端发来的.
> 
> 最近的策略好像有些变化了, 识别出握手包并不会很快把该IP加入黑名单, 已经无法识别出加入黑名单的时机了, 也无法确定解除黑名单的时机. 唯一能确定的是总有能访问的一些IP, 也总有一定丢包的一些IP, 变化的也很频繁, **目前访问GitHub IP的成功率在一半左右**. 但幸好只要握手成功, 那么该连接断开之前都能很流畅地上下行. 所以用浏览器打开的话, 只要页面打开了, 一段时间内重用该连接就一直能浏览下去.
> 
> 很明显是在温水煮青蛙了. 十四五规划里有开源建设, 说明是打算捧国内的平台了, 同时逐步弱化github.

我没墙，就是让你一会能访问一会能，让你崩溃

**Comment by diaosiqz** [comment]
> > > 即该 IP 的 443 端口超时后，只会影响你自己的宽带，不会影响和你共享公网 IP 的 NAT 下其他宽带用户。
> > 
> > 
> > 我写了个工具去测试github解析出来的一些IP, 发现确实是总有一部分能连, 一部分不能连, 即使好长时间没连过github也是如此. NAT在外面并不能分辨来源吧, 服务器只能看到一个IP从不同端口发来握手包, 但并不能分辨出哪些端口是同一终端发来的.
> > 最近的策略好像有些变化了, 识别出握手包并不会很快把该IP加入黑名单, 已经无法识别出加入黑名单的时机了, 也无法确定解除黑名单的时机. 唯一能确定的是总有能访问的一些IP, 也总有一定丢包的一些IP, 变化的也很频繁, **目前访问GitHub IP的成功率在一半左右**. 但幸好只要握手成功, 那么该连接断开之前都能很流畅地上下行. 所以用浏览器打开的话, 只要页面打开了, 一段时间内重用该连接就一直能浏览下去.
> > 很明显是在温水煮青蛙了. 十四五规划里有开源建设, 说明是打算捧国内的平台了, 同时逐步弱化github.
> 
> 我没墙，就是让你一会能访问一会不能，让你崩溃

呕  这比彻底墙掉还令人恶心

**Comment by eebssk1** [comment]
我这里是解析到ping只有几十ms的ip完全没反应，几百ms的ip到是能用，而且貌似没什么大问题

**Comment by XIU2** [comment]
2021/04/10 我这里（联通）已经出现针对 **github.io** 域名（及其子域名） SNI 阻断了，应该不会是个例。

也就是使用 **Github Pages** + Github 默认提供的 **xxx.github.io** 域名的网站，我都无法直接访问了。

**Comment by 2926295173** [comment]
ERR_CONNECTION_REFUSED
我的也是

**Comment by diaosiqz** [comment]
第十五章　打造数字经济新优势

充分发挥海量数据和丰富应用场景优势，促进数字技术与实体经济深度融合，赋能传统产业转型升级，催生新产业新业态新模式，壮大经济发展新引擎。

第一节　加强关键数字技术创新应用

聚焦高端芯片、操作系统、人工智能关键算法、传感器等关键领域，加快推进基础理论、基础算法、装备材料等研发突破与迭代应用。加强通用处理器、云计算系统和软件核心技术一体化研发。加快布局量子计算、量子通信、神经芯片、DNA存储等前沿技术，加强信息科学与生命科学、材料等基础学科的交叉创新，支持数字技术开源社区等创新联合体发展，完善开源知识产权和法律体系，鼓励企业开放软件源代码、硬件设计和应用服务。

**Comment by xljiulang** [comment]
分析得可以，如果再深入一点，把https过程分解为tcp连接+tls握手+tls数据包传输三个步骤，当你使用抓包工具抓包，你会发现，tcp连接到目标ip的443端口是没问题的，但是一但tls握手时，发送client hello环节之后，连接的数据包就被丢弃了。

我不知道本项目的6.5k星号和它能解决的问题是否名副其实，但它至少不能解决本问题。但你可能使用FastGithub，这个问题就得解。https://github.com/xljiulang/FastGithub

**Comment by 521xueweihan** [comment]
@xljiulang 你可以在这里讨论问题或者宣传你的项目，但请不要贬低别人拉高自己的项目来吸引关注。

**Comment by xljiulang** [comment]
> @xljiulang 你可以在这里讨论问题或者宣传你的项目，但请不要贬低别人拉高自己的项目来吸引关注。

我不知道“贬低别人”您 是从哪些字眼得出的，当然我没有赞赏的文字，也没有star。我陈述了项目不能解决本isssue提出的tcp rst问题，同时质疑项目的实际带来的效果与作用，如果质疑都不可以，那我去看新闻联播去了。

**Comment by dwing4g** [comment]
最近发现**移动宽带**没再对github做任何限制了, 无论是否指定host都能流畅访问. 下载Release里的文件也有几M/秒的速度.
不确定联通和电信是否也解封了.

**Comment by XIU2** [comment]
@dwing4g 经过测试，我这边联通依旧。

**Comment by dwing4g** [comment]
> 

现在移动/联通访问 20.205.243.166 这个IP能正常访问不会超时(也许只是暂时的), 该IP属于"新加坡微软云", 不是亚马逊的了.

**Comment by diaosiqz** [comment]
@XIU2   直连成功率好像提高了。移动网

**Comment by diaosiqz** [comment]
@XIU2    有空可以再测试一下 浏览器直连？

**Comment by JustinHaohao** [comment]
I need help
