### ISSUE TITLE
padavan路由器自动更新dns

### ISSUE THREAD

**Issue by a76yyyy** [521xueweihan/GitHub520#57]
我的路由器是用的padavan固件，通过如下操作来自动更新路由器的hosts信息

1.  打开浏览器进入路由器的管理页面找到：【高级设置->系统管理->服务栏】里面的计划任务 (Crontab)，如下图：
![01](https://user-images.githubusercontent.com/56478790/110428490-4b59b080-80e4-11eb-910a-3b309515db38.png)

2. 添加以下订阅代码
`0 6 * * * sed -i '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/storage/dnsmasq/hosts;wget --no-check-certificate https://raw.hellogithub.com/hosts -O /etc/storage/dnsmasq/hosts.bak;cat /etc/storage/dnsmasq/hosts.bak >> /etc/storage/dnsmasq/hosts;restart_dhcpd`

3.   ##代码解释：
3.1 前面的0 6 是代表每天06:00更新一次，时间自己也可以根据cron格式更改。
3.2 sed -i '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/storage/dnsmasq/hosts 是删除用户自定义hosts中的失效内容
3.3 wget --no-check-certificate https://raw.hellogithub.com/hosts -O /etc/storage/dnsmasq/hosts.bak;cat /etc/storage/dnsmasq/hosts.bak >> /etc/storage/dnsmasq/hosts; 下载并添加hosts内容
3.4 restart_dhcpd 重启dhcp服务加载新的hosts

**Comment by a76yyyy** [comment]
现在可以尝试一下这个，速度可能更快一些
`0 6 * * * sed -i '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/storage/dnsmasq/hosts;wget --no-check-certificate https://raw.fastgit.org/521xueweihan/GitHub520/main/hosts -O /etc/storage/dnsmasq/hosts.bak;cat /etc/storage/dnsmasq/hosts.bak >> /etc/storage/dnsmasq/hosts;restart_dhcpd`

**Comment by siwind** [comment]
对于Openwrt系统，可以这样：

40 4 * * * wget --no-check-certificate https://raw.fastgit.org/521xueweihan/GitHub520/main/hosts -O /tmp/github520.txt && sed -i '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/hosts ; cat /tmp/github520.txt >> /etc/hosts ; /etc/init.d/dnsmasq restart

**Comment by TT-IPIP** [comment]
我也是padavan，设置后日志里没显示更新host

**Comment by a76yyyy** [comment]
> 我也是padavan，设置后日志里没显示更新host

日志不显示的，可以通过“内网LAN”-“DHCP服务器”-“自定义配置文件hosts”查看更新后的信息

**Comment by TT-IPIP** [comment]
![image](https://user-images.githubusercontent.com/31797574/147175887-8b737636-cb1d-4725-affd-7f4209f499f4.jpeg)

空空如也

**Comment by mylovesaber** [comment]
#93 
我写了个教程供后来者学习自行配置，楼主那个命令有问题，属于看着没有问题但运行起来就有问题，而且出问题的地方和正确写法看不出区别的那种，直接复制楼主命令而不是自己修改的话会删除hosts 中所有规则

**Comment by TT-IPIP** [comment]
> 

用了mylovesaber的方法确实成功了

**Comment by a76yyyy** [comment]
> 用了mylovesaber的方法确实成功了


不同的padavan版本可能不一样吧，不过我确实也很久没用host了（加了旁路由用adguardhome）

**Comment by meteor0027** [comment]
> #93 我是供后来者自己写学习配置的，那个楼主命令有问题，属于看没有问题的，但是问题，出问题的地方和写法看不出有什么正确的，直接出问题的地方和写法看不出有什么正确的，直接不是命令是自己修改的话会删除hosts中所有规则 [路由器hosts配置教程](https://gitee.com/mylovesaber/auto_update_github_hosts/blob/main/%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0hosts%E6%95%99%E7%A8%8B.md)

这个方法打不开了
