### ISSUE TITLE
请教一些设置问题。

### ISSUE THREAD

**Issue by aixiu** [521xueweihan/GitHub520#58]
@521xueweihan 能不能自己托管一个。但是下边的值，不明白。求教：
···
gitee_token: ${{ secrets.GITEE_TOKEN }}
gitee_gist_id: ${{ secrets.GITEE_GIST_ID }}
gitee_gist_file_name: ${{ secrets.GITEE_GIST_FILE_NAME }}
···
请问以上三个，要填写什么，能不能给个稍详细点的说明。谢谢啦。

**Comment by 521xueweihan** [comment]
这个不用写，因为之前会把内容同步到 gitee 的 gist 中，但是gitee单方修改了服务，现在无法创建公开的 gist 了。所以我就取消了调用这个方法。

这个是 gitee 的token、gist id 和 filename

**Comment by aixiu** [comment]
感谢。。明白了。
