### ISSUE TITLE
Gitee上的自动同步连接地址

### ISSUE THREAD

**Issue by Alioth1017** [521xueweihan/GitHub520#6]
不知道Gitee上这个项目是不是博主的，更新频率挺高，下面这个地址挺好用
https://gitee.com/cnfeffery/GitHub520/raw/master/hosts

**Comment by 521xueweihan** [comment]
@Alioth1017 gitee gitst 订阅地址：https://gitee.com/xueweihan/codes/6g793pm2k1hacwfbyesl464/raw?blob_name=GitHub520.yml
