### ISSUE TITLE
SwitchHost无法自动更新Host

### ISSUE THREAD

**Issue by isomatical** [521xueweihan/GitHub520#62]
目前host还是昨天的host，软件也关闭重开了，无效。

# Update time: 2021-04-01T12:06:12+08:00
# Star me GitHub url: https://github.com/521xueweihan/GitHub520
# GitHub520 Host End

**Comment by 521xueweihan** [comment]
https://cdn.jsdelivr.net/gh/521xueweihan/GitHub520@main/hosts

我刚看了下，这个免费的 cdn 有延迟。我后面把 hosts 文件转存到国内的 cdn 届时就会即时和稳定了。
