### ISSUE TITLE
新形势下的使用教程

### ISSUE THREAD

**Issue by Z-fly** [521xueweihan/GitHub520#63]
![image](https://user-images.githubusercontent.com/10470892/113426079-84482500-9405-11eb-8ff8-374dfe9986d5.png)
手动或是使用uTools等软件编辑hosts。
完成后刷新DNS缓存。
打开浏览器访问https://github.com/ ，此时大概率访问不了。
放置一段时间，然后就可以打开了。
联通亲测OK。

**Comment by Z-fly** [comment]
#53 是可能的原理解释

**Comment by diaosiqz** [comment]
> 放置一段时间，然后就可以打开了。
让我试试

**Comment by Z-fly** [comment]
> > 放置一段时间，然后就可以打开了。
> 
> 让我试试

也许可以

**Comment by hzfvictory** [comment]
手动刷下 或者改为一分钟就可以访问了，速度还挺快

**Comment by Z-fly** [comment]
> 手动刷下 或者改为一分钟就可以访问了，速度还挺快

温水煮🐸，以后就不是一分钟就能解决的了

**Comment by 2926295173** [comment]
能解决一时是一时吧😂

**Comment by Z-fly** [comment]
> 能解决一时是一时吧😂

加速！
