### ISSUE TITLE
git push有没有办法

### ISSUE THREAD

**Issue by yueyongyue** [521xueweihan/GitHub520#66]
fatal: unable to access 'https://github.com/xxxxxx/book.git/': Failed to connect to github.com port 443: Timed out
总是超时

**Comment by any86** [comment]
没办法, 只能翻墙

**Comment by plutonemhikari** [comment]
用ssh协议push吧，配置好密钥对还可以免输入密码

**Comment by 521xueweihan** [comment]
目前没有办法
