### ISSUE TITLE
SwitchHosts  会覆盖掉hosts 导致localhost不能被解析

### ISSUE THREAD

**Issue by SweetMcdull** [521xueweihan/GitHub520#67]
![image](https://user-images.githubusercontent.com/66723003/116038535-24f3d280-a69c-11eb-8bda-75caaf10dd24.png)

**Comment by fuyz** [comment]
host配置不要少了这个：

> 127.0.0.1  	localhost

**Comment by JaySurplus** [comment]
将 系统开始默认的/etc/hosts 内容单独新建一个本地 Hosts类型， 然后在系统选项里， 选择模式->多选。


![Screenshot from 2021-05-06 11-18-57](https://user-images.githubusercontent.com/1681910/117237489-a9451300-ae5d-11eb-8f16-123bf644d7cb.png)
![Screenshot from 2021-05-06 11-18-29](https://user-images.githubusercontent.com/1681910/117237493-aba76d00-ae5d-11eb-8262-356330f4e95f.png)

**Comment by SweetMcdull** [comment]
有效👍🏻
