### ISSUE TITLE
TODO别字😘

### ISSUE THREAD

**Issue by JeremyWu917** [521xueweihan/GitHub520#7]
这里好像有一个别字。。。

![image](https://user-images.githubusercontent.com/54832272/85938736-67486800-b942-11ea-8d64-9ae9d1c22f81.png)

**Comment by 521xueweihan** [comment]
感谢您的指正，已修改：https://github.com/521xueweihan/GitHub520/commit/0d8556862895a6d8baa2b5fedb14be6a797e5998
