### ISSUE TITLE
Ubuntu下hosts文件生效

### ISSUE THREAD

**Issue by FooFooDamon** [521xueweihan/GitHub520#70]
原命令`sudo rcnscd restart`可能拼写错误，或者不是所有Linux发行版通用，实测在`Ubuntu 20.04`下应为`sudo service nscd restart`（直接执行`sudo nscd restart`会报参数个数错误），相应的安装命令为`sudo apt install nscd`，希望有所帮助。

**Comment by 521xueweihan** [comment]
好的，我改下
