### ISSUE TITLE
出现的问题

### ISSUE THREAD

**Issue by LaBiXiaoChen** [521xueweihan/GitHub520#74]
请问为什么我使用这方法之后，我进入github的速度很慢，虽然进去之后能够打开，但是访问的速度很慢，是不是这些节点的访问很慢啊

**Comment by 521xueweihan** [comment]
是的

**Comment by LaBiXiaoChen** [comment]
> 是的

请问你找到办法了吗？我感觉为了图片显示而去牺牲github页面的响应速度很不值，就没有使用了，请问你有什么比较好的解决办法吗？
