### ISSUE TITLE
建议能不能再gitee也同步更新呢?

### ISSUE THREAD

**Issue by msnh2012** [521xueweihan/GitHub520#77]
被墙了也上不了git, 要想上git得先上git找github520.

**Comment by LaBiXiaoChen** [comment]
你可以fork到你的gitee上面啊，创建一个可以同步更新的仓库就好了
下面是gitee官方提供的教程，你可以看下：
**https://gitee.com/help/articles/4284#article-header1**

**Comment by LaBiXiaoChen** [comment]
而且github一般都不会被墙，只是服务器在美国，访问很慢而已

**Comment by msnh2012** [comment]
好想法， 不过被墙是真的，好多国内研究所的IP都不容易上Git
