### ISSUE TITLE
提供一个最优解析的方案 by DoH

### ISSUE THREAD

**Issue by sky5454** [521xueweihan/GitHub520#8]
通过 带 ECS 的 DNS-Over-Https 解析即可。
比较推荐的是，IBM家的 Quad11 DNS 
`https://dns11.quad9.net/dns-query`
只有这个带 ECS
详见 https://www.quad9.net/doh-quad9-dns-servers/

我这测试的某不知名 20M 宽带可以达到秒开和满速克隆 github 仓库。

**Comment by Isildur46** [comment]
没看懂怎么使用，文章里说它支持火狐，我按照它火狐部分的操作了一遍，在 about:networking#dns 页面里也没看到 TRR 为 true 的记录。

**Comment by Isildur46** [comment]
> 
> 
> 没看懂怎么使用，文章里说它支持火狐，我按照它火狐部分的操作了一遍，在 about:networking#dns 页面里也没看到 TRR 为 true 的记录。

TRR 的 DNS 出来了，但是好像打开 github 的速度没明显变化……

**Comment by sky5454** [comment]
> 没看懂怎么使用，文章里说它支持火狐，我按照它火狐部分的操作了一遍，在 about:networking#dns 页面里也没看到 TRR 为 true 的记录。
> 更新：TRR 为 true 的 DNS 出来了，但是好像打开 github 的速度没明显变化……

构造HTTP请求即可

**Comment by athrunsun** [comment]
顺道想问一下，国内有支持DoH的DNS提供商吗？

**Comment by Oshibuki** [comment]
> 顺道想问一下，国内有支持DoH的DNS提供商吗？

360就是，是特供版
