### ISSUE TITLE
SwitchHosts 地址无法使用

### ISSUE THREAD

**Issue by lfl-0** [521xueweihan/GitHub520#82]
地址：https://raw.fastgit.org/521xueweihan/GitHub520/main/hosts
你好，上面这个地址无法使用。

**Comment by JohyC** [comment]
raw.githubusercontent.com 这个域名被dns污染了，打不开的。只能开vpn或者换个地址同步；
自推一下我写的脚本（里面有三个地址源，github gitee 国内私人服务器）
https://github.com/JohyC/Hosts；

**Comment by 521xueweihan** [comment]
@lfl-0 我做个镜像，项目中的地址也已更新
https://api.hellogithub.com/GitHub520/hosts
