### ISSUE TITLE
关于SwitchHosts问题

### ISSUE THREAD

**Issue by coder163** [521xueweihan/GitHub520#83]
hosts列表没啥问题，虽然有时候依然很慢，不过相比原来确实有所改善，按照说明文档我用的SwitchHosts，但是它会替换我本地原来的hosts内容，这就很尴尬了，虽然有切换方案，但是很容易冲突啊，有没有什么办法只更换GitHub的host其他的内容不变

**Comment by yzqdev** [comment]
> hosts列表没啥问题，虽然有时候依然很慢，不过相比原来确实有所改善，按照说明文档我用的SwitchHosts，但是它会替换我本地原来的hosts内容，这就很尴尬了，虽然有切换方案，但是很容易冲突啊，有没有什么办法只更换GitHub的host其他的内容不变
你可以改源码,追加自己的host啊,运行然后生成自己的host

**Comment by JohyC** [comment]
> hosts列表没啥问题，虽然有时候依然很慢，不过相比原来确实有所改善，按照说明文档我用的SwitchHosts，但是它会替换我本地原来的hosts内容，这就很尴尬了，虽然有切换方案，但是很容易冲突啊，有没有什么办法只更换GitHub的host其他的内容不变

有点没看懂，不是可以多个hosts列的吗？你把本地的hosts单独分一个列表呀！
![image](https://user-images.githubusercontent.com/38210128/124051775-b6424500-da4f-11eb-8a86-097e2be3ec4e.png)
![image](https://user-images.githubusercontent.com/38210128/124051788-bf331680-da4f-11eb-8397-cdb9138cf6dd.png)

**Comment by coder163** [comment]
> > hosts列表没啥问题，虽然有时候依然很慢，不过相比原来确实有所改善，按照说明文档我用的SwitchHosts，但是它会替换我本地原来的hosts内容，这就很尴尬了，虽然有切换方案，但是很容易冲突啊，有没有什么办法只更换GitHub的host其他的内容不变
> 
> 有点没看懂，不是可以多个hosts列的吗？你把本地的hosts单独分一个列表呀！
> ![image](https://user-images.githubusercontent.com/38210128/124051775-b6424500-da4f-11eb-8a86-097e2be3ec4e.png)
> ![image](https://user-images.githubusercontent.com/38210128/124051788-bf331680-da4f-11eb-8397-cdb9138cf6dd.png)

居然同时开启，万分感激
