### ISSUE TITLE
`github.blog` 没被放进去

### ISSUE THREAD

**Issue by asd-a** [521xueweihan/GitHub520#84]
不常用，但还是需要

**Comment by JohyC** [comment]
> 不常用，但还是需要

https://github.com/JohyC/Hosts 看看这里，有需要的 domain 随时提 issues；

**Comment by 521xueweihan** [comment]
@asd-a 加了

**Comment by JohyC** [comment]
> @asd-a 加了


好奇大佬的镜像是怎么同步hosts呢？我的解决方法是开启sftp，用GitHub actions上传hosts文件到我服务器。
