### ISSUE TITLE
能 ping 通但 npm install 时 GET 404

### ISSUE THREAD

**Issue by woweek** [521xueweihan/GitHub520#86]
环境：mac
现象：终端能 ping 通 codeload.github.com，解析的ip就是用您的。但 nodejs 的 pnpm install 时，总会报错
`WARN  GET https://codeload.github.com/web3-js/scrypt-shim/tar.gz/aafdadda13e660e25e1c525d1f5b2443f5eb1ebb error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.`
并且此时用 `wget https://codeload.github.com/web3-js/scrypt-shim/tar.gz/aafdadda13e660e25e1c525d1f5b2443f5eb1ebb`也能在终端里将内容下载下来。

以上操作均是在更新host并且清理本地dns缓存后的现象，实在想不明白为啥此时不能解决codeload的网络问题，还望大佬指教

**Comment by 521xueweihan** [comment]
@woweek 照你提供的信息，我感觉问题可能在 pnpm，我没用过这个工具所以没有更多的建议给你。
