### ISSUE TITLE
按照教程改了以后，有时候访问很快，有时又不能访问了

### ISSUE THREAD

**Issue by qweenhool** [521xueweihan/GitHub520#87]
电信的网，用的switchhost，查看host文件已经是修改过的，但是经常出现这种情况，无奈只能用梯子访问。

订阅地址用的：https://api.hellogithub.com/GitHub520/hosts
也加了刷新dns
![1](https://user-images.githubusercontent.com/24385912/127139043-82692e2b-8ca9-4386-821e-7c9b32231d20.png)

**Comment by CAB233** [comment]
https://github.com/521xueweihan/GitHub520/issues/53
这个issues里面也提到了，最好的办法还是挂梯吧

**Comment by pplmx** [comment]
加了后, 直接访问不了了, 太惨了
