### ISSUE TITLE
git clone 克隆项目太慢了.有啥好点的CDN节点IP不?

### ISSUE THREAD

**Issue by AtlantisDe** [521xueweihan/GitHub520#9]
git clone 克隆项目太慢了.有啥好点的CDN节点IP不?
请升级下 Host 仓库资源ip地址吧.
太慢了.下载基本几KB

**Comment by Yils-Lin** [comment]
可以先克隆到gitee，然后从gitee克隆到本地

**Comment by 521xueweihan** [comment]
@AtlantisDe  理论上已经有 github.com 对应的 IP 了，速度不应该很慢

**Comment by AtlantisDe** [comment]
> @AtlantisDe 理论上已经有 github.com 对应的 IP 了，速度不应该很慢

很慢..不知道它咋个解析的 
https://github.com/x/1.git

这样地址 按理论就是走 GitHub.com解析啊 
但是不知道原理啊  
非常慢.

**Comment by AtlantisDe** [comment]
> 可以先克隆到gitee，然后从gitee克隆到本地

gitee 没用呢 不怎么喜欢 gitee

**Comment by BoySimonHu** [comment]
直接开个终端代理~方便

**Comment by AtlantisDe** [comment]
> 直接开个终端代理~方便

嗯 看来还是买个墙外服务器方便 拖拉下载而已..没法忍受 这速度.

科学上网 下载快了...
