### ISSUE TITLE
利用gh-pages访问静态资源获取host

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [521xueweihan/GitHub520#90]
:+1:   感谢repo主提供了一个能直接访问`host`的链接 `https://raw.hellogithub.com/hosts`，解决了鸡生蛋生鸡问题 
:hushed: 不知道访问量大不大，用爱发电有无压力，这里提供一个利用`gh-pages`白嫖的思路。

<hr/>

`Settings` -> `Pages` -> 选择作为`gh-pages`的分支和路径，这里可以默认`master`和`{root}`。

那么，要我们可以访问 `521xueweihan`账号下的`GitHub520`路径为`host`的文件，访问
https://521xueweihan.github.io/GitHub520/host  即可。

进一步的，想要绑定域名或者CDN加速都是可以的。
这样即使墙域名或者IP都可以解决。

<hr/>

:flushed: 贫穷，激发了人们的想象力。

**Comment by 521xueweihan** [comment]
@nICEnnnnnnnLee 感谢您的建议，确实会有一些服务器的支持。

因为 GitHub Page 偶尔也会抽风，造成无法访问。
我测试过用 gitee 做镜像会有更新延迟。

所以，出于访问稳定和更新即时，就放到了 HK 服务器（raw.hellogithub.com）并且做了部分的镜像。

😅  为了使用体验，确实会有一些服务器的支出。
