### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by XST73** [521xueweihan/GitHub520#96]
在**switchHosts**中刷新的时候，显示_certificate has expired_

**Comment by debeetle** [comment]
同

> 在**switchHosts**中刷新的时候，显示_certificate has expired_

**Comment by IlineI** [comment]
https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

**Comment by XST73** [comment]
> https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

这个可以使用了，谢谢！
