### ISSUE TITLE
认证过期

### ISSUE THREAD

**Issue by mj5219054** [521xueweihan/GitHub520#97]
无法使用出现certificate has expired。

**Comment by cers000** [comment]
chrome访问提示
NET::ERR_CERT_DATE_INVALID

**Comment by DRPLANT666** [comment]
+1

**Comment by IlineI** [comment]
https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

**Comment by 521xueweihan** [comment]
@mj5219054 @cers000 @DRPLANT666 
已修复，请使用这个订阅地址：https://raw.hellogithub.com/hosts
