### ISSUE TITLE
认证已过期

### ISSUE THREAD

**Issue by duke326** [521xueweihan/GitHub520#98]

**Comment by IlineI** [comment]
https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

**Comment by Tename** [comment]
![image](https://user-images.githubusercontent.com/91953407/136012328-349a93d7-a2c7-4f29-9524-fe22fffe63af.png)

我遇到了这个问题，提示说证书过期。然后SwitchHost的作者对此的解答是证书过期，https://github.com/oldj/SwitchHosts/issues/640
能麻烦您解决下这个问题吗？

**Comment by duke326** [comment]
> https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts

兄弟你这个好像也不行……显示getaddrinfo ENOENT raw.githubusercontent.com

**Comment by 521xueweihan** [comment]
@duke326 
已修复，请使用这个订阅地址：https://raw.hellogithub.com/hosts
@Tename 您的感谢反馈和提供的信息，问题已修复
